name: Run PHPUnit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'  # Atualize para a versão 8.2
        extensions: mbstring, xml, pdo_mysql
        ini-values: post_max_size=256M, upload_max_filesize=256M, date.timezone=UTC
        coverage: xdebug
        tools: composer

    - name: Set execute permissions for PHPUnit
      run: chmod +x vendor/bin/phpunit
      
    - name: Run PHPUnit
      run: vendor/bin/phpunit testes/UsuarioTest.php
